=== nguyenvanthuan0398633444/CSV/ProjectTeamNET/ProjectTeamNET/SQL/Query.dtd
<!ATTLIST addif key CDATA #REQUIRED prefix CDATA #IMPLIED>
<!ATTLIST choose addStatement CDATA #IMPLIED>
<!ATTLIST query id ID #REQUIRED>
<!ELEMENT addif (#PCDATA) >
<!ELEMENT choose (addif)+ >
<!ELEMENT query (#PCDATA|addif|choose)* >
<!ELEMENT root (query)+ >

=== nguyenvanthuan0398633444/CSV/ProjectTeamNET/ProjectTeamNET/SQL/ManhourUpdateQuery.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE root SYSTEM "Query.dtd">

<root>
  <query id="SelectManhourData">
	  select
	  t1.*
	  , t2.user_name
	  , t3.theme_name1
	  , t4.work_contents_code_name
	  from
	  t_manhour AS t1
	  inner join m_user As t2
	  on t2.user_no = t1.user_no
	  inner join m_theme AS t3
	  on t3.theme_no = t1.theme_no
	  inner join m_work_contents as t4
		on t1.work_contents_code = t4.work_contents_code and t1.work_contents_class = t4.work_contents_class

	  where
	  1 = 1
	  <addif key="Year" > 
								and t1.YEAR = :Year
						</addif>
						<addif key="Month" >
								and t1.Month = :Month
						</addif>
							<addif key="Group" > 
								and t1.group_code = :Group
						</addif>
							<addif key="User" > 
								and t1.user_no = :User
						</addif>
  </query>
	<query id="SelectRole">
    select distinct(u2.function_class ), u2.screen_url
		from m_user as u1 
				inner join m_role as u2 on u1.role_code = u2.role_code
		where u2.screen_url='ManhourUpdate'
			<addif key ="user_no">
					and u1.user_no = :user_no
			</addif>		
  </query>
  
  <query id="SelectHistory">
			select * from m_user_screen_item as u
			where 1=1
			and (u.screen_item ='GROUP_CODE' or u.screen_item = 'USER_NO')	
			<addif key ="user_no">
					and u.user_no = :user_no
			</addif>
			order by u.screen_item 
  </query>
	<query id="SelectHoliday">
		SELECT
			tem.DayConver 
		FROM
			( 
					SELECT DISTINCT
							(cal.date)
							, cal.horiday
							, u.user_no
							, u.site_code
							, u.group_code
							, date_part('year', cal.date) as YearConver
							, date_part('month', cal.date) as MonthConver
							, date_part('day', cal.date) as DayConver
					FROM
							public.m_calendar as cal Join public.m_user as U 
									ON U.site_code = cal.site_code
									inner join t_manhour as m on U.user_no = m.user_no 
			) as tem 
		where
				tem.horiday = true
				<addif key="Year" > 
						and tem.YearConver = :Year
				</addif>
				<addif key="Month" >
						and tem.MonthConver = :Month
				</addif>
					<addif key="Group" > 
						and tem.group_code = :Group
				</addif>
					<addif key="User" > 
						and tem.user_no = :User
				</addif>
	</query>
	<query id="UpdateUserScreenItems">
    update public.m_user_screen_item as item
        set
						<addif key ="screenInput">
							screen_input = :screenInput
						</addif>
        where 
						1=1
						<addif key ="screenItem">
							and screen_item = :screenItem
						</addif>          
            <addif key ="userNo">
							and item.user_no = :userNo
						</addif>
  </query>
  <query id ="InsertUserScreenItems">
    INSERT
    INTO public.m_user_screen_item(
    surrogate_key
    , user_no
    , screen_url
    , screen_item
    , screen_input
    , save_name
    )
    VALUES (:Surrogate_key ,:User_no , :Screen_url , :Screen_item , :Screen_input , :Save_name );
  </query>
  <query id="UpdateManhour">
		
		UPDATE	t_manhour
	    SET		day1 = :Day1, day2 =:Day2, day3 = :Day3,day4 =:Day4,day5 = :Day5,day6 =:Day6,day7 = :Day7,day8 =:Day8,day9 = :Day9,day10 =:Day10,
				day11 =:Day11, day12 =:Day12,day13 = :Day13,day14 =:Day14,day15 = :Day15,day16 =:Day16,day17 = :Day17,day18 =:Day18,day19 = :Day19,day20 =:Day20,
				day21 =:Day21,day22 =:Day22,day23 =:Day23,day24 =:Day24,day25 =:Day25,day26 =:Day26,day27 =:Day27,day28 =:Day28,day29 =:Day29,day30 =:Day30,day31 =:Day31,
			
				pin_flg =:Pin_flg,total =:Total, fix_date =:Fix_date
		
		WHERE
				year = :Year
			AND
				month = :Month
			AND
				user_no = :User_no
			AND
				Theme_no = :Theme_no
			AND
				work_contents_class = :Work_contents_class
			AND
				work_contents_code = :Work_contents_code
			AND
				work_contents_detail = :Work_contents_detail
	</query>
  <query id="UpdateUserScreenItem">

    UPDATE  m_user_screen_item
    SET     screen_input =:ScreenInput
    WHERE
    screen_url =:ScreenUrl
    AND
    user_no =:UserNo
    AND
    screen_item = :ScreenItem
  </query>
  <query id="SelectHistoryThemeSelected">

    SELECT
    *
    FROM
    m_theme
    WHERE
    1=1
    <addif key="ThemeNo" >
      AND  theme_no = :ThemeNo
    </addif>
    <addif key="ThemeName" >
      AND theme_name1 like :ThemeName OR theme_name2 like :ThemeName
    </addif>
    <addif key="SoldFlg" >
      AND  sold_flg = :SoldFlg
    </addif>
    <addif key="GroupCode" >
      AND accounting_group_code = :GroupCode
    </addif>
    <addif key="ObjectCode" >
      AND sales_object_code = :ObjectCode
    </addif>

  </query>
  <query id="CheckExist">
    select  *
    from
    t_manhour
    where
    <addif key="Year" >
      year = :Year
    </addif>
    <addif key="Month" >
      and month = :Month
    </addif>
    <addif key="User_no" >
      and user_no = :User_no
    </addif>
    <addif key="Theme_no" >
      and theme_no = :Theme_no
    </addif>
    <addif key="Work_contents_class" >
      and work_contents_class = :Work_contents_class
    </addif>
    <addif key="Work_contents_code" >
      and work_contents_code = :Work_contents_code
    </addif>
    <addif key="Work_contents_detail" >
      and work_contents_detail = :Work_contents_detail
    </addif>	
  </query>
  <query id="SelectWorkContent">

		SELECT DISTINCT work_contents_code, work_contents_code_name  
		FROM			m_work_contents
		ORDER BY		work_contents_code

	</query>
   <query id="CheckImport">
    select  *
    from
    t_manhour
    where
    <addif key="Year" >
      year = :Year
    </addif>
    <addif key="Month" >
      and month = :Month
    </addif>
    <addif key="User_no" >
      and user_no = :User_no
    </addif>
    <addif key="Theme_no" >
      and theme_no = :Theme_no
    </addif>   
    <addif key="Work_contents_code" >
      and work_contents_code = :Work_contents_code
    </addif>
    <addif key="Work_contents_detail" >
      and work_contents_detail = :Work_contents_detail
    </addif>	
  </query>
  
  <query id="SelectWorkContent">

		SELECT DISTINCT work_contents_code, work_contents_code_name  
		FROM			m_work_contents
		ORDER BY		work_contents_code

	</query>
  
  <query id="SelectUser">
    select * 
    from m_user
    where
    <addif key="userNo" >
       user_no = :userNo
    </addif>
  </query>
  
<query id="SelectWordContenClass">
     select work_contents_class 
      from m_theme
      where
      <addif key="themeNo" >
        theme_no = :themeNo
      </addif>   
  </query>
  <query id="UpdateUserScreenItem">

    UPDATE  m_user_screen_item
    SET     screen_input =:ScreenInput
    WHERE
    screen_url =:ScreenUrl
    AND
    user_no =:UserNo
    AND
    screen_item = :ScreenItem
  </query>
  <query id="SelectHistoryThemeSelected">

    SELECT
    *
    FROM
    m_theme
    WHERE
    1=1
    <addif key="ThemeNo" >
      AND  theme_no = :ThemeNo
    </addif>
    <addif key="ThemeName" >
      AND theme_name1 like :ThemeName OR theme_name2 like :ThemeName
    </addif>
    <addif key="SoldFlg" >
      AND  sold_flg = :SoldFlg
    </addif>
    <addif key="GroupCode" >
      AND accounting_group_code = :GroupCode
    </addif>
    <addif key="ObjectCode" >
      AND sales_object_code = :ObjectCode
    </addif>

  </query>
  <query id="SelectWorkContent">

    SELECT DISTINCT work_contents_code, work_contents_code_name
    FROM			m_work_contents
    ORDER BY		work_contents_code

  </query>


</root>

=== nguyenvanthuan0398633444/CSV/ProjectTeamNET/ProjectTeamNET/SQL/ManCheckHour.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE root SYSTEM "Query.dtd">

<root>
	<!-- メニュー情報取得 -->
	<query id="SelectWorkContents">
		<![CDATA[
		select * from m_work_contents order by work_contents_code 
    ]]>
	</query>

	<query id="SelectManhourData">
		<![CDATA[
		SELECT
			t1.*,t2.theme_name1,t2.theme_name2,t3.work_contents_code,t3.work_contents_code_name
		FROM 
				t_manhour t1
			JOIN m_theme t2
			ON t1.theme_no = t2.theme_no 
			JOIN m_work_contents t3 
			ON t3.work_contents_class = t1.work_contents_class
		WHERE 
				t1.year = 2021
			AND t1.month = 7
			AND t1.user_no = '01'

		ORDER BY 
			t2.theme_no
	]]>
	</query>
	<query id ="SelectWorkHourOfMonth">
		select * from (SELECT MH.user_no, MH.Day1,MH.Day2,MH.Day3,MH.Day4,MH.Day5,MH.Day6,MH.Day7,MH.Day8,MH.Day9,MH.Day10,MH.Day11,MH.Day12,MH.Day13,MH.Day14,MH.Day15,MH.Day16,MH.Day17,MH.Day18,MH.Day19,MH.Day20,MH.Day21,MH.Day22,MH.Day23,MH.Day24,MH.Day25,MH.Day26,MH.Day27,MH.Day28,MH.Day29,MH.Day30,MH.Day31
		,Case WHEN MH.month &gt;= 0 AND MH.month &lt;= 9
		THEN concat(MH.year,'0',MH.month )
		WHEN MH.month &gt;= 10
		Then concat(MH.year,Cast(MH.month as text) )
		END as duration
		FROm public.t_manhour as MH) as tem
		INNER Join public.m_processing_month as pm On duration = pm.processing_month
		WHERE tem.user_no = user_no
		<addif key="user_no" >
			AND tem.user_no = :user_no
		</addif>
		ORDER BY tem.user_no ASC
		LIMIT 1

	</query>
	<query id ="GetHoliday">
		SELECT * FROM (SELECT
		DISTINCT(cal.date),
		cal.horiday,
		u.user_no,
		u.site_code,
		date_part('year', cal.date)  as YearConver,
		date_part('month', cal.date)  as MonthConver
		FROM public.m_calendar as cal
		Join public.m_user as U ON U.site_code = cal.site_code) as tem
		WHERE
		1 = 1
		<addif key="user_no" >
			AND tem.user_no =:user_no
		</addif>	
		<addif key="YearConver" >
			AND tem.YearConver =:currentYear
		</addif>	
		<addif key="MonthConver" >
			AND tem.MonthConver =:currentMonth
		</addif>

	</query>
	<query id ="GetWorkHourOfMonth">
		SELECT * FROM public.t_manhour as MH
		WHERE 
		1 = 1 
		<addif key="user_no" >
		   AND	MH.user_no = :user_no
		</addif>		
		<addif key="year" >
			AND MH.year = :year
		</addif>		
		<addif key="month" >
			AND MH.month = :month
		</addif>

	</query>
	<query id ="GetUserInfo">
		SELECT
		 U.user_no
		,U.role_code
		,U.site_code
		,U.group_code
		FROM
		public.m_user as U
		WHERE		
		<addif key="user_no" >
			U.user_no = :user_no
		</addif>
	</query>
</root>

=== nguyenvanthuan0398633444/CSV/ProjectTeamNET/ProjectTeamNET/SQL/ManhourInput.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE root SYSTEM "Query.dtd">

<root>
	<!-- メニュー情報取得 -->

	<query id="SelectManhourDatas">

		SELECT
				t1.*
				,t2.theme_name1
				,t3.work_contents_class_name
				,t4.work_contents_code_name
		FROM	t_manhour AS t1
				JOIN m_theme AS t2				ON t1.theme_no = t2.theme_no
				JOIN m_work_contents_class t3	ON t1.work_contents_class = t3.work_contents_class
				JOIN m_work_contents t4			ON t1.work_contents_class = t4.work_contents_class and t1.work_contents_code = t4.work_contents_code
		WHERE
					1 = 1
				<addif key="Year" > 
					AND t1.YEAR = :Year
				</addif>    
				<addif key="Month" >
					AND t1.Month = :Month
				</addif>
				<addif key="User_no" > 
					 AND t1.user_no = :User_no
				</addif>
		ORDER BY
				t1.theme_no
	</query>

	<query id="SelectManhour">

		SELECT
		t1.year
		,t1.month
		,t1.user_no
		,t1.theme_no
		,t1.work_contents_code
		,t1.work_contents_class
		,t1.work_contents_detail
		FROM	t_manhour AS t1
		WHERE
			1=1
			AND t1.year = :Year

			AND t1.month = :Month

			AND t1.user_no = :User_no

			AND t1.theme_no = :Theme_no

			AND t1.work_contents_class = :Work_contents_class

			AND t1.work_contents_code = :Work_contents_code

			AND t1.work_contents_detail = :Work_contents_detail

	</query>
	
	<query id="SelectScreenItem">
		SELECT 
			*
		FROM 
			m_user_screen_item
		WHERE 
					1=1
			<addif key="User_no" > 
				AND   user_no = :User_no
            </addif> 
		
			<addif key="Screen_url" > 
				AND screen_url = :Screen_url
			</addif> 
	</query>

	<query id="SelectPinTheme">
		<![CDATA[
		SELECT
				t1.user_no
				,t1.year
				,t1.month
				,t1.group_code
				,t1.site_code
				,t1.theme_no
				,t1.work_contents_class
				,t1.work_contents_code
				,t1.work_contents_detail
		FROM
				t_manhour t1
				JOIN m_theme t2
				ON t1.theme_no = t2.theme_no
		WHERE
			1=1
		AND
			t1.year = :Year
		AND
			t1.month = :Month
		AND
			t1.pin_flg = true
		AND
			t1.user_no = :User_no
		order by
			t2.theme_no
    ]]>
	</query>	
	
	<query id="SelectHistoryTheme">

		SELECT
			*
		FROM 
			m_theme
		WHERE 
				1=1 
			<addif key="ThemeNo" > 
            AND  theme_no = :ThemeNo 
            </addif> 
			<addif key="ThemeName" > 
			AND theme_name1 like :ThemeName OR theme_name2 like :ThemeName
			</addif>
			<addif key="SoldFlg" > 
            AND  sold_flg = :SoldFlg 
            </addif> 
			<addif key="GroupCode" > 
			AND accounting_group_code = :GroupCode 
			</addif>
			<addif key="ObjectCode" > 
			AND sales_object_code = :ObjectCode 
			</addif>
			
	</query>
	<query id="UpdateManhour">
		
		UPDATE	t_manhour
	    SET		day1 = :Day1, day2 =:Day2, day3 = :Day3,day4 =:Day4,day5 = :Day5,day6 =:Day6,day7 = :Day7,day8 =:Day8,day9 = :Day9,day10 =:Day10,
				day11 =:Day11, day12 =:Day12,day13 = :Day13,day14 =:Day14,day15 = :Day15,day16 =:Day16,day17 = :Day17,day18 =:Day18,day19 = :Day19,day20 =:Day20,
				day21 =:Day21,day22 =:Day22,day23 =:Day23,day24 =:Day24,day25 =:Day25,day26 =:Day26,day27 =:Day27,day28 =:Day28,day29 =:Day29,day30 =:Day30,day31 =:Day31,
				pin_flg =:Pin_flg,total =:Total, fix_date =:Fix_date
		
		WHERE
				year = :Year
			AND
				month = :Month
			AND
				user_no = :User_no
			AND
				Theme_no = :Theme_no
			AND
				work_contents_class = :Work_contents_class
			AND
				work_contents_code = :Work_contents_code
			AND
				work_contents_detail = :Work_contents_detail
	</query>

	<query id="ChangeManhour">

		UPDATE	t_manhour
		SET		theme_no = :NewTheme_no, work_contents_class =:NewWork_contents_class,work_contents_code = :NewWork_contents_code
				,work_contents_detail = :NewWork_contents_detail

		WHERE
				year = :Year
				AND
				month = :Month
				AND
				user_no = :User_no
				AND
				theme_no = :Theme_no
				AND
				work_contents_class = :Work_contents_class
				AND
				work_contents_code = :Work_contents_code
				AND
				work_contents_detail = :Work_contents_detail
	</query>
	<query id="UpdateManhourDay">
		
		UPDATE	t_manhour
	    SET		{0} = :Day, pin_flg =:Pin_flg, total =:Total, fix_date =:Fix_date
		
		WHERE
				year = :Year
			AND
				month = :Month
			AND
				user_no = :User_no
			AND
				Theme_no = :Theme_no
			AND
				work_contents_class = :Work_contents_class
			AND
				work_contents_code = :Work_contents_code
			AND
				work_contents_detail = :Work_contents_detail
	</query>
	<query id="UpdateManhourWeek">
		
		UPDATE	t_manhour
	    SET		{0} = :Day1, {1} =:Day2, {2} = :Day3, {3} =:Day4, {4} = :Day5, {5} =:Day6, {6} = :Day7
				,pin_flg =:Pin_flg,total =:Total, fix_date =:Fix_date
		
		WHERE
				year = :Year
			AND
				month = :Month
			AND
				user_no = :User_no
			AND
				Theme_no = :Theme_no
			AND
				work_contents_class = :Work_contents_class
			AND
				work_contents_code = :Work_contents_code
			AND
				work_contents_detail = :Work_contents_detail
	</query>
	
	<query id="DeleteManhour">
		
		DELETE FROM t_manhour
		WHERE
				year = :Year
			AND
				month = :Month
			AND
				user_no = :User_no
			AND
				Theme_no = :Theme_no
			AND
				work_contents_class = :Work_contents_class
			AND
				work_contents_code = :Work_contents_code
			AND
				work_contents_detail = :Work_contents_detail
	</query>

	<query id="UpdateUserScreenItem">

		UPDATE  m_user_screen_item
		SET     screen_input =:ScreenInput
		WHERE
					screen_url =:ScreenUrl
				AND 
					user_no =:UserNo
				AND 
					screen_item = :ScreenItem
	</query>

	<query id="SelectGroupCode">

		SELECT	  DISTINCT accounting_group_code, accounting_group_name
		FROM	  m_group
		ORDER BY  accounting_group_code

	</query>

	<query id="SelectWorkContent">

		SELECT work_contents_class, work_contents_code, work_contents_code_name  
		FROM			m_work_contents
		ORDER BY		work_contents_code

	</query>
	<query id="UpdatePage">

		UPDATE  m_user_screen_item
		SET		screen_item = :ScreenItem
		WHERE
				screen_url =:ScreenUrl
			AND 
				user_no =:UserNo
	</query>

	<query id="SelectHorliday">

		SELECT	DATE_PART('day', date)
		FROM	m_calendar
		WHERE
				DATE_PART('year', date) = :Year
				AND DATE_PART('month',date) = :Month
				AND horiday = true
				AND site_code =:SiteCode
		ORDER BY DATE_PART('day', date)
	</query>

	<query id="UpdatePinTheme">

		UPDATE  t_manhour
		SET		pin_flg = false
		WHERE
					year = :Year
				AND
					month = :Month
				AND
					user_no = :User_no
				AND
					Theme_no = :Theme_no
				AND
					work_contents_class = :Work_contents_class
				AND
					work_contents_code = :Work_contents_code
				AND
					work_contents_detail = :Work_contents_detail
	</query>

	<query id="SelectByWorkClass">
		SELECT work_contents_code,work_contents_code_name
		FROM m_work_contents
		WHERE work_contents_class =:Work_contents_class
	</query>
	

</root>

=== nguyenvanthuan0398633444/CSV/ProjectTeamNET/ProjectTeamNET/SQL/ManhourReport.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE root SYSTEM "Query.dtd">

<root>
	<!-- メニュー情報取得 -->
	<query id="SelectCompany">
		<![CDATA[
	select company_name As name from m_company
    ]]>
	</query>

	<query id="GroupName">
		<![CDATA[
		select group_code, concat(group_code, '[',group_name, '  ', accounting_group_name,']') As GroupName from m_group
		]]>
	</query>
	
	<query id="queryManReport">
		select
           mh.year
			, mh.month
			, mh.user_no as UserCode
			, u.user_name as UserName
			, mh.group_code as GroupCode 
			, gr.group_name as GroupName
			, mh.theme_no as ThemeCode
			, th.theme_name1 as ThemeName
			, mh.work_contents_code as WorkContentCode
			, mh.work_contents_detail as WorkContentDetail
			, wc.work_contents_code_name as WorkContentCodeName
        from
            public.t_manhour as mh join public.m_theme as th 
                on mh.theme_no = th.theme_no join public.m_group as gr 
                on gr.group_code = mh.group_code join public.m_user as u 
                on u.user_no = mh.user_no join public.m_work_contents wc 
                on wc.work_contents_code = mh.work_contents_code and wc.work_contents_class = mh.work_contents_class
        where
		1=1
		<addif key ="More2YearDiffrence">
			and ((mh.year = :fromYear and mh.month &gt;= :fromMonth) or (mh.year = :toYear and mh.month &lt;= :toMonth) or (mh.year in(:fromYear +1,:toYear -1)))
		</addif>
		<addif key ="More1YearDiffrence">
			and ((mh.year = :fromYear and mh.month &gt;= :fromMonth) or (mh.year = :toYear and mh.month &lt;= :toMonth))
		</addif>
		<addif key ="SameYear">
			and mh.year = :toYear and mh.month in(:fromMonth,:toMonth)
		</addif>
		<addif key ="Group_User">
			and :user = mh.user_no and :groupCode = mh.group_code
		</addif>
		<addif key ="Theme_WorkContent">
			and :workThemeContent LIKE '%' || CONCAT(mh.theme_no, mh.work_contents_code, mh.work_contents_detail) || '%'
		</addif>
		<addif key ="Theme_WorkContent_nodetail">
			and :workThemeContent LIKE '%' || CONCAT(mh.theme_no, mh.work_contents_code) || '%'
		</addif>
			
	</query>

	<query id="queryManReport1">
		select
		mh.year
		, mh.month
		, mh.user_no as UserCode
		, u.user_name as UserName
		, mh.group_code as GroupCode
		, gr.group_name as GroupName
		, mh.theme_no as ThemeCode
		, th.theme_name1 as ThemeName
		, mh.work_contents_code as WorkContentCode
		, mh.work_contents_detail as WorkContentDetail
		, wc.work_contents_code_name as WorkContentCodeName
		from
		public.t_manhour as mh join public.m_theme as th
		on mh.theme_no = th.theme_no join public.m_group as gr
		on gr.group_code = mh.group_code join public.m_user as u
		on u.user_no = mh.user_no join public.m_work_contents wc
		on wc.work_contents_code = mh.work_contents_code and wc.work_contents_class = mh.work_contents_class
		where
		1=1
		<addif key ="More2YearDiffrence">
			and ((mh.year = :fromYear and mh.month &gt;= :fromMonth) or (mh.year = :toYear and mh.month &lt;= :toMonth) or (mh.year in(:fromYear +1,:toYear -1)))
		</addif>
		<addif key ="More1YearDiffrence">
			and ((mh.year = :fromYear and mh.month &gt;= :fromMonth) or (mh.year = :toYear and mh.month &lt;= :toMonth))
		</addif>
		<addif key ="SameYear">
			and mh.month &lt;= :toMonth and  mh.year = :toYear and mh.month &gt;= :fromMonth
		</addif>
		<addif key ="GroupContent">
			and :groupContent LIKE '%' || CONCAT(mh.group_code,mh.work_contents_code, mh.work_contents_detail) || '%'
		</addif>
		<addif key ="WorkContent">
			and :workContent LIKE '%' || CONCAT(mh.work_contents_code, mh.work_contents_detail) || '%'
		</addif>

	</query>

</root>
